version: "3.9"

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [front, api]

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    restart: unless-stopped
    env_file:
      - ./front/.env.production

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    env_file:
      - ./api/.env.production

volumes:
  caddy_data:
  caddy_config:
